### ISSUE TITLE
Call of createDelegation in _submitJobs

### ISSUE THREAD

**Issue by maikenp** [jakobmerljak/pyarcrest#2]
The call to createDelegation: https://github.com/jakobmerljak/pyarcrest/blob/7e1daafafc932651ebaf7eb6dce6d412e391009f/src/pyarcrest/arc.py#L803
has the possibility to pass a token and a proxypath. 
However, these parameters are not passed to the _submitJobs where createDelegation is called from. 

Is this just forgotten, or is there some other way createDelegation gets hold of the token or proxypath which I did not spot? 

Otherwise, _submitJobs should maybe instead of this: 

```
def _submitJobs(self, descs, queue, delegationID=None, processDescs=True, matchDescs=True, uploadData=True, workers=None, sendsize=None, timeout=None, v1_0=False):
```

be: 

```
def _submitJobs(self, descs, queue, delegationID=None, processDescs=True, matchDescs=True, uploadData=True, token=None, proxypath=None, workers=None, sendsize=None, timeout=None, v1_0=False):
```

Or are you thinking that in this use-case one would just call createDelegation directly before calling submitJobs, and then passing the delegationID in the submitjobs call?

**Comment by jakobmerljak** [comment]
I forgot to consider this call of `createDelegation` but I think it is preferable to only operate with the delegation for this method (and most of the rest of the API). I think this makes the API cleaner as it sticks to a single way of auth, using delegations instead of both delegations and "raw" credentials from which the delegation is created implicitly. It also reflects the REST API better.

And it doesn't change the way the `token` and `proxypath` parameters need to be managed. As you noted, they are used in `createDelegation` call before `submitJobs` instead of being passed to it directly.
